// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACk2R-45IZaPbZ6nsa1DJ4z5XwGLGhuZc',
    appId: '1:556615603228:web:388f3b9be390bf6ef3bbd9',
    messagingSenderId: '556615603228',
    projectId: 'boom-d7450',
    authDomain: 'boom-d7450.firebaseapp.com',
    storageBucket: 'boom-d7450.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcSwPYAPWkcBFW0QiV0lwP5XfdddA4ys',
    appId: '1:556615603228:android:8aa8ab6a3fd8ccb3f3bbd9',
    messagingSenderId: '556615603228',
    projectId: 'boom-d7450',
    storageBucket: 'boom-d7450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5WELaIihqQI-q-zpF4QIu1j5LMQHYYrw',
    appId: '1:556615603228:ios:8f8605772f4e0e1df3bbd9',
    messagingSenderId: '556615603228',
    projectId: 'boom-d7450',
    storageBucket: 'boom-d7450.firebasestorage.app',
    iosClientId: '556615603228-enj14f5d7372ajllrkul0vfdv9no7581.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5WELaIihqQI-q-zpF4QIu1j5LMQHYYrw',
    appId: '1:556615603228:ios:8f8605772f4e0e1df3bbd9',
    messagingSenderId: '556615603228',
    projectId: 'boom-d7450',
    storageBucket: 'boom-d7450.firebasestorage.app',
    iosClientId: '556615603228-enj14f5d7372ajllrkul0vfdv9no7581.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACk2R-45IZaPbZ6nsa1DJ4z5XwGLGhuZc',
    appId: '1:556615603228:web:2bd1a98ba02d0658f3bbd9',
    messagingSenderId: '556615603228',
    projectId: 'boom-d7450',
    authDomain: 'boom-d7450.firebaseapp.com',
    storageBucket: 'boom-d7450.firebasestorage.app',
  );
}
